### PR TITLE
fix(iOS): Use joinOnce 

### PR DESCRIPTION
**Pull request by eliaslecomte**
Fix for iOS 13 as mentioned https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/2.

### CODE REVIEW

**Comment by Rapsssito** [comment]
Could you please rename the PR, so it follows the [semantic-release commit gidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines)?

**Comment by eliaslecomte** [comment]
> @eliaslecomte, could you please rename the PR, so it follows the [semantic-release commit gidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines)?

Sure

**Comment by JuanSeBestia** [comment]
has conflicts :(

**Pull request merged**
