### PR TITLE
docs: Add location permission example code

### PR DESCRIPTION
**Pull request by eliaslecomte**
Fine location is required for getting the wifi networks around you or connecting with a protected network. Let adds a little more information on this on the readme.

### CODE REVIEW

**Comment by Rapsssito** [comment]
@eliaslecomte, LGTM!

**Comment by Rapsssito** [comment]
@eliaslecomte, I added some details and created a PR to your fork: https://github.com/inthepocket/react-native-wifi-reborn/pull/10. Could you check it out?

**Comment by eliaslecomte** [comment]
That looks good, I wouldn't have removed the fb documentation link but no problem. You don't need to create PR's directed to https://github.com/inthepocket/react-native-wifi-reborn/ as we will merge changes from https://github.com/JuanSeBestia/react-native-wifi-reborn/ every now and then.

**Comment by eliaslecomte** [comment]
I'll add your changes to this PR later today or tomorrow.

**Comment by JuanSeBestia** [comment]
It happens in iOS on versión 13, but I add the logic of request the permission inside the getSSID functionality, I'm not sure if I was a good idea that is an anti-pattern that you write in android.

I'm a little confused :s

**Comment by eliaslecomte** [comment]
In an Android library you typically leave that logic to the library user, as they may want to set a specific text or add logic if the user denies it.

I would expect that to be the same on iOS? Not 100% sure but I did notice that this function asked the permission by itself on iOS. Maybe we should ask an iOS veteran @bitcrumb?

**Comment by bitcrumb** [comment]
@JuanSeBestia I would agree with @eliaslecomte that it would be more flexible to let the user of the react-native-wifi-reborn library decide when to show the location permission dialog.

I think this can be easily accomplished simply by adding the following code in a a separate method to the user (similar to how Elias did for Android):
`[self.locationManager requestWhenInUseAuthorization];`

This way the user of your library can decide where he wants to ask for permission in the user flow of his app & if he wants to accompany it with some extra visual information.

Also, I'm not sure that location permissions are required on iOS when only calling getSSID. For example, in the app Elias and I are working on, we have set the **NEHotspotConfiguration** capability in Xcode (since we are using methods of this app that use `NEHotspotConfigurationManager`). This alone should be sufficient to be able to access the current SSID. See screenshot below:

Screenshot 2020-03-18 at 06 47 52

I don't see any mentionof the **NEHotspotConfiguration** in your documentation. Is this an oversight?

**Comment by Rapsssito** [comment]
Using [React Native Permissions](https://github.com/react-native-community/react-native-permissions) will **allow the developer to ask for the user permissions in Android and iOS**. It has been added to the example in the documentation.

**Comment by bitcrumb** [comment]
Yes, it also crossed my mind that it's better to rely on that library to ask for permissions. But does that imply that you will remove location permissions checks in react-native-wifi-reborn?

**Comment by eliaslecomte** [comment]
In android, it is checked if the required permission has been given, if not, we reject the promise with an appropriate error code.

**Comment by Rapsssito** [comment]
@bitcrumb, I agree with @eliaslecomte, we will just reject the promise with a message about asking for permission.

**Comment by bitcrumb** [comment]
Sounds exactly how I would do it as well :)

**Comment by JuanSeBestia** [comment]
Okay, I will remove this functionality en native part of iOS on reference the location permission and put the example in Doc

**Pull request merged**
