### PR TITLE
Check repeatedly for matching SSID on iOS

### PR DESCRIPTION
**Pull request by elliottkember**
I've found locally that sometimes the `completionHandler` for `[NEHotspotConfigurationManager sharedManager] applyConfiguration` returns before the network is fully connected. 

There is an Apple Support thread about this here: https://developer.apple.com/forums/thread/111379 -

> NEHotspotConfigurationManager calls its completion handler as soon as it has dealt with the request, that is, as soon as it has checked the request and passed it on to that Wi-Fi infrastructure. This has a significant impact on users of NEHotspotConfigurationManager: You can’t be guaranteed that the device has actually joined the Wi-Fi network by the time your completion handler is called. In fact this won’t be the case most of the time.
> If there’s an error joining the Wi-Fi network, that error is reported to the user, not via your completion handler.

This patch checks the connected SSID every 0.5 seconds for 10 seconds, to see whether it's connected. I've been testing this locally and it seems to work great, so thought I should submit it for review in case this is helpful or I'm doing something wrong.

### CODE REVIEW

**Comment by elliottkember** [comment]
Bumping this pull request, because we've been using it locally with great results ever since. This is a useful addition for connecting to small devices like 360 cameras (that's our use case).

**Comment by JuanSeBestia** [comment]
At the moment I can't test it, if some other mantainers like @eliaslecomte or @gitisaac want to test, approve and merge it, go ahead

**Comment by alexma01** [comment]
Hi guys,

can we merge this PR?

Thanks

**Comment by JuanSeBestia** [comment]
@alexma01 are you already test it?

**Comment by elliottkember** [comment]
@bitcrumb A pleasure. Very happy to see this merged. It was nice to delete the patch we've been using. We haven't had any problems since this patch, so hoping others see the same great results.

**Pull request merged**
