### PR TITLE
Minor bug fix, iOS 15 getWifiSSID fix, connect to Android Wifi without scanning (because of the limit)

### LINKED ISSUE #246: IOS 15 getWifiSSID
We are having issue getting current wifi SSID on IOS 15.

We are getting error "Cannot detect SSID". We have added location permission but still having same issue

Seems like getWifiSSID returing nil

It works using Xcode but not working when generating IPA and installing on actual device 

Please help

### PR DESCRIPTION
**Pull request by SpiriaJWF**
I don't know if this will be accepted because it contains huge changes, but I think it would be appreciate by the community. It handles iOS 15 new getWifiSSID and doesn't scan wifi on Android before connecting to it. This PR also contains some refactoring and minor bug fix.

fix #246

### CODE REVIEW

**Comment by drash-course** [comment]
Can this PR be reviewed and merged? We are already using this patch successfully on iOS for our app.

**Comment by JuanSeBestia** [comment]
I will squash this MR to use angular semantic commits to work with semantic-release. See more here: https://github.com/semantic-release/semantic-release#how-does-it-work

**Comment by JuanSeBestia** [comment]
@SpiriaJWF Thanks for your contribution, I add you as collaborator for this repo :)

**Pull request merged**
