### PR TITLE
Feature/update gradle configuration

### PR DESCRIPTION
**Pull request by eliaslecomte**
Awesome you take up maintenance of react-native-wifi 😉.
In this PR:
* add gradle wrapper (so the android folder can be loaded in Android Studio)
* add correct repositories to the build.gradle
* target latest android sdk

### CODE REVIEW

**Comment by JuanSeBestia** [comment]
image
I tried to directly compile the library in Android Studio and it has launched this error, maybe it has something to do with https://stackoverflow.com/questions/45834070/getcurrentactivity-is-not-public-com-facebook-react-bridge-react-context-canno

Maybe it's not important, i'm not sure

**Comment by JuanSeBestia** [comment]
In the same way I tried it, and the functionality of obtaining the wifi works correctly

**Comment by eliaslecomte** [comment]
Hey Juan, I will open PR that fixes that exception + improve the android implementation as well soon.

**Comment by JuanSeBestia** [comment]
@eliaslecomte Awesome :)

**Pull request merged**
