### PR TITLE
fix: set timeout param for iOS as nonnull instead of nullable, as React requires

### LINKED ISSUE #379: v4.12.x produces a runtime error when `connectToProtectedSSID` is called on iOS
I've found that by upgrading the version of `react-native-wifi-reborn` I'm using from version `4.11.0` to `4.12.0` (or `4.12.1`), my app produces the runtime error shown in the screenshot below on my iOS devices. (I have not had the chance to check on Android, but am happy to if it would help investigations).

image

Text content of the image below:

`Argument 4 (NSNumber) of WifiManager.connectToProtectedSSIDis marked as nullable but React requires that all NSNumber arguments are explicitly marked as nonnull' to ensure compatibility with Android.`

More than happy to try contribute/assist, so please do let me know if you need more information, or if there is anything I can do to assist in resolving the issue.

### LINKED ISSUE #396: iOS : Argument 4 (NSNumber) of WifiManager.connectToProtectedSSID is marked as nullable
i'm facing this iOS issue in the latest version of react native wifi reborn package while calling the function :

**WifiManager.connectToProtectedSSID**

this is how I'm using it:

 WifiManager.connectToProtectedSSID(ssid, API.pIDevicePassword, false)

I think this is an issue in Pod file content where it is asking a parameter to be marked as nullable. Please suggest and provide guidance on how to fix it.

Argument 4 (NSNumber) of WifiManager.connectToProtectedSSID is marked as nullable but React requires that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
-[RCTModuleMethod processMethodSignature]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_root_queue_drain_deferred_wlh
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

### PR DESCRIPTION
**Pull request by DavideViolante**
Fix #396 
Fix #379 

I honestly don't know if this is correct, I used [this conversation with ChatGPT](https://chatgpt.com/share/c7ba66de-ee88-4583-aa86-f9a08635b249) to help me fix this error.

This PR absolutely requires at least one review from someone that know this code and language.

cc @JuanSeBestia @alexma01

### CODE REVIEW

**Comment by alexma01** [comment]
Hi @DavideViolante and sorry for delay :)

I think the suggested modification is correct, but i don't have time to test it, have you tested it?

**Comment by DavideViolante** [comment]
I didn't test it actually, I just noticed a couple of issues with same error since latest version and tried to fix it. 
@JuanSeBestia can you check this PR out please?

**Comment by JuanSeBestia** [comment]
I can't test it at the moment. but if you test it and works I will merge it

**Comment by keith-kurak** [comment]
This fixed the error on my end once I added the 5th parameter to my call to `connectToProtectedSSID`. (updating the readme, as well, would probably be good)

**Comment by DavideViolante** [comment]
I'd merge this one @JuanSeBestia

**Comment by DavideViolante** [comment]
I can't merge by myself

**Pull request merged**
