### PR TITLE
feat(Android): added feature to connect to hidden wifi on android 10

### PR DESCRIPTION
**Pull request by gitisaac**
I was using react-native-wifi-reborn for a project that needed the feature to connect to a device with a hidden WiFi. With these changes, I was able to connect to the device using `WifiManager.connectToProtectedSSID` (with Android 10+).

### CODE REVIEW

**Comment by JuanSeBestia** [comment]
Do you still need this?

**Comment by gitisaac** [comment]
That would be nice, yes! I am currently using [patch-package](https://www.npmjs.com/package/patch-package) to include my changes in my project.

**Comment by JuanSeBestia** [comment]
Ohhhh, thanks for sharing it, I didn't know that it exist... I will try to resolve the conflicts

**Comment by JuanSeBestia** [comment]
Hmmmmmm, I tried to resolve the conflicts with github.com, but I'm not sure, 

image

can you resolve the conflicts and merge it. you have conflicts with https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/264. I invite you as collaborators, welcome :)

**Comment by JuanSeBestia** [comment]
Please use a semantic-commit in your commit message like 

feat(Android) added feature to connect to hidden wifi on android 10

Then this git action would create a new version

**Pull request merged**
