### PR TITLE
fix(Android): getCurrentWifiSSID return null if '<unknown ssid>'

### PR DESCRIPTION
**Pull request by eliaslecomte**
Sometimes while switching network, android returns <unknown ssid>.
You aren't connected, so let's simply return an empty string.

### CODE REVIEW

**Comment by eliaslecomte** [comment]
Actually what happens on iOS if you are not connected? Is empty string returned or an exception?

**Comment by Rapsssito** [comment]
@eliaslecomte, looking at the code:

https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/1049665912ef6382b39de85da4b3bb32d529b896/ios/RNWifi.m#L35-L46

It looks like iOS returns `nil` when no SSID is found.

**Comment by eliaslecomte** [comment]
> @eliaslecomte, looking at the code:
> 
> https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/1049665912ef6382b39de85da4b3bb32d529b896/ios/RNWifi.m#L35-L46
> 
> It looks like iOS returns `nil` when no SSID is found.

Thanks! I've aligned this with Android :-).

**Comment by Rapsssito** [comment]
@eliaslecomte, taking a deeper look, it looks like when get a `null` SSID in iOS, we reject the promise with the message `"Cannot detect SSID"`.

https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/1049665912ef6382b39de85da4b3bb32d529b896/ios/RNWifi.m#L183-L192

What do you think? Should we also reject in Android or change the iOS part in order to return null too?

**Comment by eliaslecomte** [comment]
@Rapsssito I've changed the Android code to also reject in this case.

**Pull request merged**
