### PR TITLE
Fix gradle elvis resolution

### PR DESCRIPTION
**Pull request by stryaponoff**
Elvis can't be resolved when trying to access forceWifiUsageWithOptions() after 4.3.0 update

### CODE REVIEW

**Comment by AntoinedeChassey** [comment]
@JuanSeBestia please merge this PR 😇 (4.3.0 is broken otherwise, just an import being forgotten)
Thx in advance

**Comment by eliaslecomte** [comment]
I'm still confused, we shouldn't add the dependencies voor WifiUtils. I guess it's due to it's move from java to kotlin. I'll try to fix this. This can be merged as temporary fix, or apps that use 4.3.0 could add this in their own build.gradle.

**Comment by ThanosFisherman** [comment]
Sorry about that guys I believe there was an issue with the `maven-publish` plugin not resolving [Elvis](https://github.com/ThanosFisherman/Elvis) automatically. Elvis

Please try the new version `1.6.4` of WifiUtils and let me know if everything is ok this time. If not well I'll do some more digging. As a last resort try including Elvis library manually (but I wouldn't really prefer that).

**Comment by eliaslecomte** [comment]
WifiUtils released a new version: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/122

**Comment by eliaslecomte** [comment]
> Sorry about that guys I believe there was an issue with the `maven-publish` plugin not resolving [Elvis](https://github.com/ThanosFisherman/Elvis) automatically. Elvis
> 
> Please try the new version `1.6.4` of WifiUtils and let me know if everything is ok this time. If not well I'll do some more digging. As a last resort try including Elvis library manually like you already did in this PR (but I wouldn't really prefer that).

Thanks for your quick help! I don't think Elvis has to be transitive btw.

**Comment by eliaslecomte** [comment]
4.3.1 is released 🎊!

**Pull request closed without merging**
