### PR TITLE
Reconcile loadWifiList type declaration

### PR DESCRIPTION
**Pull request by marcotoniut**

### CODE REVIEW

**Comment by eliaslecomte** [comment]
Does it really return a string 😢?

**Comment by marcotoniut** [comment]
Yep 😅

**Comment by notjulian** [comment]
> Does it really return a string 😢?

yes it does
also reScanAndLoadWifiList(): Promise<Array<string>>

it will not be better return alway an Array<WifiEntry>?

anyway thanks

**Comment by eliaslecomte** [comment]
This really is a bug.. I've fixed it, and it's in PR: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/104

**Pull request closed without merging**
