### PR TITLE
fix(Android): targetSdkVersion 28, previously connected network compatibility & recently added network compatibility

### PR DESCRIPTION
**Pull request by Rapsssito**
# Features
### targetSdkVersion 28
Right now, there is **no need** for targeting `targetSdkVersion 29` since the library works with Android 10. Only when the Android 10 compatibility patch is released or RN upgrades to `targetSdkVersion 29`, will be needed.

### Previously connected network compatibility
Previously connected networks were throwing an error when trying to connect to them.

### Recently added network compatibility
Recently created networks were throwing an error when trying to connect to them as if they were not in range. This was caused after the encryption search if the result was `null`. Now, if the resulting encryption is `null`, we guess the network uses `WPA2` instead of throwing an error.

### CODE REVIEW

**Comment by Rapsssito** [comment]
@JuanSeBestia hope you can merge this!

**Comment by JuanSeBestia** [comment]
Can you see the conflicts? please

**Comment by Rapsssito** [comment]
> 
> 
> Can you see the conflicts? please

@JuanSeBestia, done!

**Comment by JuanSeBestia** [comment]
It is a bit tedious to review your changes with so many changes of indentation :(

**Comment by JuanSeBestia** [comment]
Thanks soo mucho to use semantic-release

**Comment by Rapsssito** [comment]
> 
> 
> It is a bit tedious to review your changes with so many changes of indentation :(

Yeah, sorry about that...

**Comment by Rapsssito** [comment]
@JuanSeBestia could you release a the version, please?

**Comment by JuanSeBestia** [comment]
Pro tip: if you include commits in semantic-release, this PR is deployed when is merged.

**Pull request merged**
