### PR TITLE
feat: Add loadWifiList meaningfull Exceptions

### PR DESCRIPTION
**Pull request by eliaslecomte**
This PR improves the loadWifiList feature. It rejects with a meaningfull exception when it couldn't scan.

**Errors**
* `locationPermissionMissing`: Starting android 6, location permission needs to be granted for wifi 
* `locationServicesOff`: Starting Android 6, location services needs to be on to scan for wifi networks.
* `jsonParsingException`: Json parsing exception while parsing the result.
* `illegalViewOperationException`: An exception caused by JS requesting the UI manager to perform an illegal view operation.

### CODE REVIEW

**Comment by eliaslecomte** [comment]
I've did this because of this request: https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/75

**Comment by Rapsssito** [comment]
Android side looks good. Currently testing the JS and TypeScript parts.

**Comment by Rapsssito** [comment]
@eliaslecomte, could you create a dummy commit on this branch so the new automated tests can execute?

**Pull request merged**
