### PR TITLE
BREAKING CHANGE: Use WifiUtils to connect with a wifi network

### PR DESCRIPTION
**Pull request by eliaslecomte**
Starting Android 10, it's no longer possible to connect (as an app) to wifi networks like before.

What can an app still do:

Temporary connect to a wifi access point (for example to setup an IoT device)
Suggest a network, but the OS can choose what to do with it.
With this PR, i've switched the connection logic to use WifiUtils which just released support for option 1.

Advantages of using WifiUtils:

Works well on different android versions
Only resolves when the app is connected to the network
Has a good retry mechanism built in
Well written code

### CODE REVIEW

**Comment by eliaslecomte** [comment]
It is true that the android 10 support from WifiUtils is still early. We have tested this on multiple android devices and when we have good fixes, we will contribute to WifiUtils and react-native-wifi-reborn.

**Comment by Rapsssito** [comment]
As mentioned here (https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/28#issuecomment-578100838), right now, you can connect to open WiFi networks passing `null` as password. Could you confirm if this is still the case with this change?

**Comment by Rapsssito** [comment]
@JuanSeBestia, why would this be a BREAKING CHANGE?

**Comment by eliaslecomte** [comment]
> @JuanSeBestia, why would this be a BREAKING CHANGE?

Because this is a hefty change regardign connecting on Android. For one, it uses new code for pre android 10 and starting 10 it's also completely different in it's way, that only the current app can use the wifi network.

**Comment by Rapsssito** [comment]
@eliaslecomte, for semantic-release compatibility, could you add to your initial post a "BREAKING CHANGE: <message>" following the [AngularJS Git Commit Convention](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#breaking-changes)?

**Comment by Rapsssito** [comment]
@eliaslecomte, should we wait for @JuanSeBestia opinion?
LGTM. It will fix a lot of future issues and focuses our work in JavaScript and Objective-C.

**Comment by eliaslecomte** [comment]
I do think @JuanSeBestia  should approve :-).

**Comment by JuanSeBestia** [comment]
1. When you do a commit changing readme like `chore: update the readme` you would use the prefix docs, like `docs: update the readme`
2. Really looks very clean code in android
3. We forgot iOS :(

We want to clarify changing  the versión in the readme if someone need the previous version, wich versión would need to install

In the nutshell, I will allow marge this MR :)

**Pull request merged**
