### PR TITLE
perf: Reduce package size

### PR DESCRIPTION
**Pull request by Rapsssito**
- Removed `.npmignore` and added the `files` entry on `package.json`.
- Encapsulated `index.js` file in a `src/` folder for a clearer repository structure.
- Added some gradle generated files to the `.gitignore`.

### CODE REVIEW

**Comment by eliaslecomte** [comment]
Why remove the gradle.properties, the wrapper & gradlew script?

**Comment by Rapsssito** [comment]
> 
> 
> Why remove the gradle.properties, the wrapper & gradlew script?

@eliaslecomte, I removed those files because are automatically generated by Android Studio and we are not using them in the repo. The main reason was to reduce the git repo size when cloning. However, we can keep them, they do not harm anyone.

**Comment by Rapsssito** [comment]
@eliaslecomte, I've added the gradle files back.

**Comment by eliaslecomte** [comment]
> @eliaslecomte, I've added the gradle files back.

Nice! Although Android Studio can generate them, it's best everyone building the android code does it under the same conditions / with the same scripts. Different Android Studio's versions might have resulted in subtle changes or build failures.

**Pull request merged**
